name: feature_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8
  - plyfile=0.8.1
  - tqdm
  - cmake
  - ninja
  - git
  - pip
  - pip:
      - natsort
      - scikit-image
      - opencv-python
      - -e thirdparty/mmcv
      - thirdparty/gaussian_splatting/submodules/gaussian_rasterization_ch9
      - thirdparty/gaussian_splatting/submodules/gaussian_rasterization_ch3
      - thirdparty/gaussian_splatting/submodules/forward_full
      - thirdparty/gaussian_splatting/submodules/forward_lite
      - thirdparty/gaussian_splatting/submodules/simple-knn
